const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const moduleCode = ts.transpileModule(fs.readFileSync('lib/scan.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
const scan = { exports: {} };
new Function('exports', 'require', 'module', moduleCode)(scan.exports, require, scan);
const { calibrateScan, validateScan, sampleImage, classifyColor, SCAN_FACES } = scan.exports;
const palette = ['#ed259a', '#7130ca', '#10bcb1', '#eeeeee', '#eeee20', '#ed6d12'];
const faces = SCAN_FACES.map((face, index) => ({ ...face, stickers: Array(9).fill(palette[index]), samples: Array(9).fill(palette[index]) }));
assert.equal(validateScan(calibrateScan(faces)).valid, true, 'Custom colors are valid without default colors');
assert.equal(classifyColor(113, 48, 202), '#7130ca', 'Unknown colors stay intact');
assert.equal(classifyColor(100, 42, 180, palette), '#7130ca', 'Shaded purple matches purple');
const duplicate = faces.map((face) => ({ ...face, stickers: [...face.stickers] }));
duplicate[1].stickers[4] = duplicate[0].stickers[4];
assert.equal(validateScan(duplicate).valid, false);
assert.equal(validateScan(faces.slice(0, 5)).valid, false);
const pixels = new Uint8ClampedArray(64 * 64 * 4);
for (let i = 0; i < pixels.length; i += 4) pixels.set(i < 400 ? [255, 255, 255, 255] : [113, 48, 202, 255], i);
let drawArgs;
const canvas = { getContext: () => ({ drawImage: (...args) => { drawArgs = args; }, getImageData: () => ({ data: pixels }) }) };
assert.deepEqual(sampleImage({}, canvas, { x: 50, y: 70, size: 300 }), Array(9).fill('#7130ca'), 'Highlights do not wash out median color');
assert.deepEqual(drawArgs.slice(1), [50, 70, 300, 300, 0, 0, 480, 480], 'Samples the guide crop');
console.log('Scan regression checks passed');
