const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const moduleCode = ts.transpileModule(fs.readFileSync('lib/scan.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
const scan = { exports: {} };
new Function('exports', 'require', 'module', moduleCode)(scan.exports, require, scan);
const { calibrateScan, correctScanFaces, orientScanFaces, rotateStickers, validateScan, sampleImage, classifyColor, SCAN_FACES } = scan.exports;
const cubeCode = ts.transpileModule(fs.readFileSync('lib/cube.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
const cubeModule = { exports: {} };
new Function('exports', 'require', 'module', cubeCode)(cubeModule.exports, require, cubeModule);
const cube = cubeModule.exports;
const palette = ['#ed259a', '#7130ca', '#10bcb1', '#eeeeee', '#eeee20', '#ed6d12'];
const faces = SCAN_FACES.map((face, index) => ({ ...face, stickers: Array(9).fill(palette[index]), samples: Array(9).fill(palette[index]) }));
assert.equal(validateScan(calibrateScan(faces)).valid, true, 'Custom colors are valid without default colors');
assert.equal(classifyColor(113, 48, 202), '#7130ca', 'Unknown colors stay intact');
assert.equal(classifyColor(100, 42, 180, palette), '#7130ca', 'Shaded purple matches purple');
const cameraPalette = ['#f4f1e8', '#e33027', '#1f9a55', '#f4c92d', '#eb7a24', '#2875d9'];
assert.equal(classifyColor(24, 66, 145, cameraPalette), '#2875d9', 'A shadowed blue keeps its hue classification');
assert.equal(classifyColor(116, 40, 31, cameraPalette), '#e33027', 'A dark red does not become orange under uneven lighting');
const duplicate = faces.map((face) => ({ ...face, stickers: [...face.stickers] }));
duplicate[1].stickers[4] = duplicate[0].stickers[4];
assert.equal(validateScan(duplicate).valid, false);
assert.equal(validateScan(faces.slice(0, 5)).valid, false);
const legalState = cube.applyMoves(cube.cloneState(cube.SOLVED_STATE), ["R", "U", "F2", "L'", "D"]);
const legalFaces = SCAN_FACES.map((face) => ({ ...face, stickers: legalState[face.code] }));
assert.equal(validateScan(legalFaces).valid, true, 'Legal move sequences pass the physical-state check');
const rotatedPhotos = legalFaces.map((face, index) => ({ ...face, stickers: rotateStickers(face.stickers, [1, 2, 3, 0, 1, 2][index]) }));
assert.equal(validateScan(rotatedPhotos).valid, false, 'Unaligned face photos are rejected before correction');
const automaticallyAligned = orientScanFaces(rotatedPhotos);
assert.equal(validateScan(automaticallyAligned).valid, true, 'Face rotations are automatically aligned into a legal state');
assert.ok(automaticallyAligned.some((face) => face.orientation), 'Automatic alignment records the applied face rotations');
const swappedScan = legalFaces.map((face) => ({ ...face, stickers: [...face.stickers], samples: [...face.stickers] }));
[swappedScan.find((face) => face.code === "U").stickers[7], swappedScan.find((face) => face.code === "F").stickers[1]] = [swappedScan.find((face) => face.code === "F").stickers[1], swappedScan.find((face) => face.code === "U").stickers[7]];
assert.equal(validateScan(swappedScan).valid, false, 'An ambiguous two-sticker scan mistake is detected');
assert.equal(validateScan(correctScanFaces(swappedScan)).valid, true, 'The majority-correct scan recovers a legal arrangement');
const flippedEdge = legalFaces.map((face) => ({ ...face, stickers: [...face.stickers] }));
[flippedEdge.find((face) => face.code === "U").stickers[7], flippedEdge.find((face) => face.code === "F").stickers[1]] = [flippedEdge.find((face) => face.code === "F").stickers[1], flippedEdge.find((face) => face.code === "U").stickers[7]];
const flippedValidation = validateScan(flippedEdge);
assert.equal(flippedValidation.valid, false, 'A single flipped edge is rejected');
assert.ok(flippedValidation.issues.some((issue) => issue.stickers.some((sticker) => sticker.face === "U" && sticker.index === 7)), 'A flipped edge identifies its exact sticker');
const twistedCorner = legalFaces.map((face) => ({ ...face, stickers: [...face.stickers] }));
const u = twistedCorner.find((face) => face.code === "U").stickers;
const r = twistedCorner.find((face) => face.code === "R").stickers;
const f = twistedCorner.find((face) => face.code === "F").stickers;
[u[8], r[0], f[2]] = [r[0], f[2], u[8]];
assert.equal(validateScan(twistedCorner).valid, false, 'A single twisted corner is rejected');
const pixels = new Uint8ClampedArray(64 * 64 * 4);
for (let i = 0; i < pixels.length; i += 4) pixels.set(i < 400 ? [255, 255, 255, 255] : [113, 48, 202, 255], i);
let drawArgs;
const canvas = { getContext: () => ({ drawImage: (...args) => { drawArgs = args; }, getImageData: () => ({ data: pixels }) }) };
assert.deepEqual(sampleImage({}, canvas, { x: 50, y: 70, size: 300 }), Array(9).fill('#7130ca'), 'Highlights do not wash out median color');
assert.deepEqual(drawArgs.slice(1), [50, 70, 300, 300, 0, 0, 480, 480], 'Samples the guide crop');
console.log('Scan regression checks passed');
